REPO_DRIVER="https://github.com/frederik-h/acer-wmi-battery.git"
DRIVER_REVISION="9f90d75cc9237aeed7964622d10dbdf4d2c7b518"
DRIVER_MODULE="acer-wmi-battery"
DKMS_NAME="acer-wmi-battery"
DKMS_VERSION="0.1.0.archer1"
SOURCE_FILE="acer-wmi-battery.c"
MODULE_LOCATION="."
DKMS_VERSION_BASE="0.1.0"
